-- Migration: Add lead_gen_conversations table for public chatbot
-- Date: 2026-02-17
-- Purpose: Store conversations from the public-facing lead generation chatbot.
--          Separate from the internal `conversations` table so we can track
--          prospect-specific data (contact info, matched programs, CTA selection)
--          without touching the auth-protected conversation infrastructure.
--
-- Note: session_id is a UUID string generated by the application and passed back
--       to the client. It doubles as the conversationId used in the `conversations`
--       table (for runAgent message history storage).

CREATE TABLE IF NOT EXISTS lead_gen_conversations (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id       TEXT        NOT NULL UNIQUE,  -- Client-facing ID; also maps to conversations.id
  ip_address       TEXT,                          -- For rate limiting (max 3 new sessions/IP/hour)
  messages         JSONB       NOT NULL DEFAULT '[]',  -- Snapshot of full [{role, content}] history
  prospect_data    JSONB       NOT NULL DEFAULT '{}',  -- Extracted info: company, province, industry, revenue, hiring, training, expansion, etc.
  matched_programs JSONB       NOT NULL DEFAULT '[]',  -- Programs returned from grant search
  estimated_funding TEXT,
  cta_selected     TEXT,                           -- 'book_call' | 'getgranted' | 'email_summary' | 'none'
  contact_name     TEXT,
  contact_email    TEXT,
  hubspot_contact_id TEXT,
  status           TEXT        NOT NULL DEFAULT 'active',  -- 'active' | 'completed' | 'abandoned'
  message_count    INTEGER     NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast lookup by session_id (primary query path)
CREATE INDEX IF NOT EXISTS idx_lead_gen_conversations_session_id
  ON lead_gen_conversations(session_id);

-- Rate limiting: count recent sessions per IP
CREATE INDEX IF NOT EXISTS idx_lead_gen_conversations_ip_created
  ON lead_gen_conversations(ip_address, created_at);

-- Status filtering
CREATE INDEX IF NOT EXISTS idx_lead_gen_conversations_status
  ON lead_gen_conversations(status);

-- Trigger to auto-update updated_at on every row change
CREATE OR REPLACE FUNCTION update_lead_gen_conversation_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_lead_gen_conversation_timestamp
BEFORE UPDATE ON lead_gen_conversations
FOR EACH ROW
EXECUTE FUNCTION update_lead_gen_conversation_timestamp();

COMMENT ON TABLE lead_gen_conversations IS
  'Public-facing lead generation chatbot sessions. Each row represents one visitor conversation. '
  'session_id is returned to the browser and used as conversationId in the internal conversations '
  'table for runAgent message history. ip_address enables per-IP rate limiting.';

COMMENT ON COLUMN lead_gen_conversations.session_id IS
  'UUID string returned to the browser as the session token. Also used as conversations.id for runAgent.';
COMMENT ON COLUMN lead_gen_conversations.messages IS
  'Full [{role, content}] conversation snapshot. Kept in sync on every turn for easy export.';
COMMENT ON COLUMN lead_gen_conversations.prospect_data IS
  'Extracted prospect profile: company, province, industry, revenue, employees, hiring_plans, '
  'training_plans, export_plans, founded_year, business_type, owner_demographics, etc.';
COMMENT ON COLUMN lead_gen_conversations.matched_programs IS
  'Grant programs returned by search_getgranted during this session.';
COMMENT ON COLUMN lead_gen_conversations.cta_selected IS
  'Which CTA the prospect clicked: book_call | getgranted | email_summary | none.';
COMMENT ON COLUMN lead_gen_conversations.status IS
  'Session lifecycle: active (in progress) | completed (CTA taken) | abandoned (timed out).';
