-- Migration 017: Add Smart Tags JSONB Column
-- Created: 2026-03-09
-- Purpose: Add structured tagging to improve grant search ranking and categorization

-- ========================================
-- NEW COLUMN
-- ========================================

-- JSONB column for structured tags generated by Claude Haiku
-- Fields: primary_intents, genres, max_funding_numeric, specificity, complexity, target_populations, funding_model
ALTER TABLE grants ADD COLUMN IF NOT EXISTS smart_tags JSONB DEFAULT NULL;

-- ========================================
-- INDEX
-- ========================================

-- GIN index for JSONB column (enables fast queries on nested fields)
CREATE INDEX IF NOT EXISTS idx_grants_smart_tags ON grants USING gin(smart_tags);

-- ========================================
-- VERIFICATION
-- ========================================

DO $$
DECLARE
  total_count INTEGER;
  tagged_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO total_count FROM grants;
  SELECT COUNT(*) INTO tagged_count FROM grants WHERE smart_tags IS NOT NULL;

  RAISE NOTICE '✅ Migration 017 complete:';
  RAISE NOTICE '   Total grants: %', total_count;
  RAISE NOTICE '   Grants with smart_tags: %', tagged_count;
  RAISE NOTICE '';
  RAISE NOTICE '⚠️  NOTE: smart_tags will be NULL until batch tagging is run.';
  RAISE NOTICE '   Run: node src/services/grant-tagger-batch.js';
END $$;
