-- Migration 025: Store proposed high-risk actions until a human confirms them
--
-- WHY
-- src/tools/executor.js gated three tools behind an input flag (`confirmed: true`)
-- and said so itself: "This is a forcing function, not a security boundary. A
-- model could set confirmed: true on the first call." HubSpot writes had no code
-- gate at all — their rail was a sentence in .claude/agents/internal-oracle.md.
-- Worse, what the user approved was the model's PARAPHRASE of the action, while
-- the call that eventually ran was built separately and could differ from it.
--
-- The gate now saves the exact tool name and input here instead of running it,
-- code writes the confirmation text from this row, and code runs THIS row when
-- the user says yes. The model never re-states the action and cannot bypass it.
--
-- ONE PENDING ACTION PER CONVERSATION
-- Enforced by a partial unique index, not by convention, so a race between two
-- proposals in one thread cannot leave two rows a "yes" could ambiguously match.
-- A new proposal supersedes the old one rather than queueing.
--
-- SUMMARY IS STORED, NOT REGENERATED
-- The confirmation replays the text the user actually read. If the summary code
-- changes between proposal and confirmation, the stored wording still governs.
--
-- EXPIRY
-- expires_at is set 24 hours out at insert. A stale "yes" in a quiet thread must
-- not fire an action proposed yesterday against data that has since moved.
--
-- Idempotent and safe to re-run.

CREATE TABLE IF NOT EXISTS pending_actions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  tool_name       TEXT NOT NULL,
  tool_input      JSONB NOT NULL,
  summary         TEXT NOT NULL,
  proposed_by     INTEGER REFERENCES users(id),
  status          TEXT NOT NULL DEFAULT 'pending',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ NOT NULL,
  confirmed_by    INTEGER REFERENCES users(id),
  confirmed_at    TIMESTAMPTZ,
  result          JSONB
);

COMMENT ON TABLE pending_actions IS
  'High-risk tool calls saved instead of executed, awaiting a human "yes". Written by the confirmation gate in src/tools/executor.js; read and run by runPendingAction in src/tools/pending-actions.js.';

COMMENT ON COLUMN pending_actions.tool_input IS
  'The exact input the model proposed. This is what runs on confirmation — it is never rebuilt from the conversation.';

COMMENT ON COLUMN pending_actions.summary IS
  'Plain-language text generated by code and shown to the user. Stored so confirmation replays exactly what was read.';

COMMENT ON COLUMN pending_actions.status IS
  'pending | confirmed | superseded | expired | failed. Only one pending row per conversation (see the partial unique index).';

COMMENT ON COLUMN pending_actions.proposed_by IS
  'User whose turn caused the proposal. May differ from confirmed_by: anyone in the conversation may confirm.';

-- The invariant, in the database rather than in a comment: at most one pending
-- row per conversation, so a "yes" always resolves to exactly one action.
CREATE UNIQUE INDEX IF NOT EXISTS pending_actions_one_per_conversation
  ON pending_actions (conversation_id)
  WHERE status = 'pending';

-- Expiry sweeps and audit queries both filter on status first.
CREATE INDEX IF NOT EXISTS idx_pending_actions_status_expires
  ON pending_actions (status, expires_at);
