/**
 * Grant Cards - Granted Insights Quality Tests
 *
 * Integration test using LLM-as-judge to evaluate the strategic value
 * and quality of Granted Insights generated by the grant-cards agent.
 * Tests Category C (Quality & Strategic Value).
 */

const { sendMessageToAgent } = require('../utils/test-helpers');
const { gradeWithLLM, createInsightRubric } = require('../utils/llm-grader');

describe('Grant Cards - Granted Insights Quality (LLM-Graded)', () => {

  describe('Strategic Insight Generation', () => {

    test('Generated insights meet professional quality standards', async () => {
      const grantDoc = `
Innovation Boost Program for Manufacturing

Funding Amount: $50,000 - $500,000 (max 50% of project costs)

Eligibility:
- BC-based manufacturing companies
- Minimum 2 years in operation
- Annual revenue $500,000 - $50,000,000
- Must implement new technology or process innovation

Eligible Projects:
- Automation and robotics
- Advanced manufacturing processes
- Quality control systems
- Energy efficiency improvements

Evaluation Criteria:
- Innovation potential (30%)
- Economic benefit (25%)
- Technical feasibility (20%)
- Company capacity (15%)
- Market opportunity (10%)

Application Process:
- Pre-qualification required
- Two-stage application
- Technical review by expert panel
- Decision within 90 days

Deadline: September 30, 2026
Application Fee: $500 (non-refundable)
      `.trim();

      const response = await sendMessageToAgent(
        'grant-cards',
        grantDoc,
        { task: 'insights' }
      );

      // Grade the strategic insights quality
      const grading = await gradeWithLLM({
        task: 'Generate strategic Granted Insights for grant opportunity',
        output: response.content,
        rubric: createInsightRubric(),
        context: grantDoc
      });

      // Should meet quality threshold (4.0+ out of 5)
      expect(grading).toMeetQualityThreshold(4.0);

      // Should score well on key dimensions
      expect(grading.scores.depth_of_strategic_insight_not_generic_advice).toBeGreaterThanOrEqual(3.5);
      expect(grading.scores.actionability_for_client_decision_making).toBeGreaterThanOrEqual(4);

      console.log('\n📊 Granted Insights Quality Grading:');
      console.log(`   Overall Score: ${grading.overallScore}/5`);
      console.log(`   Feedback: ${grading.feedback}\n`);

    }, 60000);

  });

  describe('Competitive Intelligence Value', () => {

    test('Insights provide competitive intelligence beyond basic program info', async () => {
      const grantDoc = `
Clean Technology Accelerator

Competitive grant for cleantech startups in BC.

Funding: $75,000 (non-repayable contribution)

Eligibility:
- Cleantech focus (renewable energy, waste reduction, water tech)
- Early-stage (seed to Series A)
- BC headquarters
- Must have working prototype
- Revenue under $5M

Selection Criteria:
- Technology innovation (40 points)
- Market potential (30 points)
- Team strength (20 points)
- Environmental impact (10 points)

Additional Support:
- Mentorship from industry experts
- Access to testing facilities
- Connections to investors
- Marketing support

Application: Rolling intake (quarterly cohorts)
Success Rate: ~15% of applicants funded
      `.trim();

      const response = await sendMessageToAgent(
        'grant-cards',
        grantDoc,
        { task: 'insights' }
      );

      // Custom rubric focused on competitive intelligence
      const grading = await gradeWithLLM({
        task: 'Evaluate competitive intelligence and strategic positioning advice in Granted Insights',
        output: response.content,
        rubric: {
          criteria: [
            'Provides insider knowledge beyond publicly available info',
            'Identifies competitive advantages or positioning strategies',
            'Offers specific, actionable recommendations (not generic)',
            'Highlights success factors for this specific program',
            'Warns about common pitfalls or rejection reasons'
          ],
          scale: '1-5 where 5 is excellent competitive intelligence'
        },
        context: grantDoc
      });

      // Competitive intelligence should be strong
      expect(grading.overallScore).toBeGreaterThanOrEqual(3.5);

      // Should contain strategic advice
      const content = response.content.toLowerCase();
      expect(content.length).toBeGreaterThan(200); // Substantive insights

      console.log('\n📊 Competitive Intelligence Score:');
      console.log(`   Score: ${grading.overallScore}/5`);
      console.log(`   Strategic Value: ${grading.feedback}\n`);

    }, 60000);

  });

  describe('Insight Formatting and Conciseness', () => {

    test('Insights are concise, well-formatted, and actionable', async () => {
      const grantDoc = `
Digital Transformation Grant

Funding: Up to $150,000 (50% cost-share)

For: SMEs adopting digital technologies (cloud, AI, automation, e-commerce)

Requirements:
- 5-200 employees
- Technology implementation plan required
- Must engage approved technology consultant

Eligible Costs:
- Software licenses
- Hardware and equipment
- Implementation services
- Employee training
- Change management

Deadline: March 31, 2026
      `.trim();

      const response = await sendMessageToAgent(
        'grant-cards',
        grantDoc,
        { task: 'insights' }
      );

      // Check formatting requirements
      const content = response.content;

      // Insights should be bulleted or clearly separated
      expect(content).toMatch(/[-•*]|\n\d\./); // Contains bullets or numbers

      // Grade formatting and clarity
      const grading = await gradeWithLLM({
        task: 'Evaluate formatting, conciseness, and actionability of Granted Insights',
        output: response.content,
        rubric: {
          criteria: [
            'Insights are presented in clear bullet points (3-4 points)',
            'Each insight is one sentence maximum (concise)',
            'Insights are immediately actionable (tell client what to do)',
            'Professional tone appropriate for consultant',
            'No unnecessary jargon or filler language'
          ],
          scale: '1-5 where 5 is perfectly formatted and actionable'
        },
        context: grantDoc
      });

      // Formatting should be excellent
      expect(grading.overallScore).toBeGreaterThanOrEqual(4.0);

      // Should contain 3-4 distinct insights (approximately)
      const bulletPoints = (content.match(/[-•*]|\n\d\./g) || []).length;
      expect(bulletPoints).toBeGreaterThanOrEqual(2);
      expect(bulletPoints).toBeLessThanOrEqual(6);

      console.log('\n📊 Insight Formatting & Conciseness:');
      console.log(`   Score: ${grading.overallScore}/5`);
      console.log(`   Bullet Points: ${bulletPoints}`);
      console.log(`   Feedback: ${grading.feedback}\n`);

    }, 60000);

  });

  describe('Next Steps and Call to Action', () => {

    test('Insights include clear next steps for contacting Grant Consultant', async () => {
      const grantDoc = `
Agriculture Innovation Program

Funding for agricultural technology adoption.
Amount: $25,000 - $200,000
Eligible: Farms and agri-businesses in BC
Focus: Precision agriculture, automation, sustainability technologies
Deadline: June 30, 2026
      `.trim();

      const response = await sendMessageToAgent(
        'grant-cards',
        grantDoc,
        { task: 'insights' }
      );

      const content = response.content.toLowerCase();

      // Should include call to action about contacting consultant
      expect(content).toMatch(/contact|reach out|connect|speak with|grant consultant|next step/);

      // Grade call to action effectiveness
      const grading = await gradeWithLLM({
        task: 'Evaluate the effectiveness of the call to action / next steps in Granted Insights',
        output: response.content,
        rubric: {
          criteria: [
            'Includes clear next steps for the client',
            'Encourages contacting the Grant Consultant',
            'Creates urgency or compelling reason to act',
            'Natural conclusion to the insights (not forced)',
            'Professional and consultative tone'
          ],
          scale: '1-5 where 5 is highly compelling call to action'
        }
      });

      expect(grading.overallScore).toBeGreaterThanOrEqual(3.5);

      console.log('\n📊 Call to Action Effectiveness:');
      console.log(`   Score: ${grading.overallScore}/5`);
      console.log(`   Assessment: ${grading.feedback}\n`);

    }, 60000);

  });

});
